// <auto-generated />
using System;
using AuHackathon2025.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuHackathon2025.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250620090804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("AuHackathon2025.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeCount = 12,
                            Name = "Architecture"
                        },
                        new
                        {
                            Id = 2,
                            EmployeeCount = 8,
                            Name = "Administration"
                        },
                        new
                        {
                            Id = 3,
                            EmployeeCount = 15,
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = 4,
                            EmployeeCount = 25,
                            Name = "Development"
                        });
                });

            modelBuilder.Entity("AuHackathon2025.Models.StorageUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StorageGB")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("StorageUsages");
                });

            modelBuilder.Entity("AuHackathon2025.Models.StorageUsage", b =>
                {
                    b.HasOne("AuHackathon2025.Models.Department", "Department")
                        .WithMany("StorageUsages")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AuHackathon2025.Models.Department", b =>
                {
                    b.Navigation("StorageUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
